package br.com.orcamentop.negocio;

import br.com.orcamentop.dto.ListaProduto;
import br.com.orcamentop.dto.ListaProdutoHelper;
import br.com.orcamentop.dto.Produto;
import br.com.orcamentop.dto.ProdutoHelper;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Properties;
import org.omg.CORBA.MARSHAL;
import org.omg.CORBA.ORB;
import org.omg.CORBA.portable.ApplicationException;
import org.omg.CORBA.portable.Delegate;
import org.omg.CORBA.portable.InputStream;
import org.omg.CORBA.portable.ObjectImpl;
import org.omg.CORBA.portable.OutputStream;
import org.omg.CORBA.portable.RemarshalException;

/**
 * br/com/orcamentop/negocio/_ControllerProdutoStub.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.2" from orcamentop.idl Domingo,
 * 10 de Junho de 2018 23h26min58s BRT
 */
public class _ControllerProdutoStub extends ObjectImpl implements ControllerProduto {

    private static String[] __ids = {
        "IDL:br/com/orcamentop/negocio/ControllerProduto:1.0"};
    
    @Override
    public boolean gravar(Produto produto) {
        InputStream in = null;
        
        try {
            OutputStream out = _request("gravar", true);
            ProdutoHelper.write(out, produto);
            in = _invoke(out);
            boolean result = in.read_boolean();
            return result;
        } catch (ApplicationException ex) {
            in = ex.getInputStream();
            String _id = ex.getId();
            throw new MARSHAL(_id);
        } catch (RemarshalException rm) {
            return gravar(produto);
        } finally {
            _releaseReply(in);
        }
    }

    @Override
    public boolean remover(Produto produto) {
        InputStream in = null;
        try {
            OutputStream out = _request("remover", true);
            ProdutoHelper.write(out, produto);
            in = _invoke(out);
            boolean result = in.read_boolean();
            return result;
        } catch (ApplicationException ex) {
            in = ex.getInputStream();
            String _id = ex.getId();
            throw new MARSHAL(_id);
        } catch (RemarshalException rm) {
            return remover(produto);
        } finally {
            _releaseReply(in);
        }
    }

    @Override
    public ListaProduto carregar() {
        InputStream in = null;
        
        try {
            OutputStream out = _request("carregar", true);
            in = _invoke(out);
            ListaProduto result = ListaProdutoHelper.read(in);
            return result;
        } catch (ApplicationException ex) {
            in = ex.getInputStream();
            String _id = ex.getId();
            throw new MARSHAL(_id);
        } catch (RemarshalException rm) {
            return carregar();
        } finally {
            _releaseReply(in);
        }
    }

    @Override
    public String[] _ids() {
        return (String[]) __ids.clone();
    }

    private void readObject(ObjectInputStream s) throws IOException {
        String str = s.readUTF();
        String[] args = null;
        Properties props = null;
        ORB orb = ORB.init(args, props);
        
        try {
            Object obj = orb.string_to_object(str);
            Delegate delegate = ((ObjectImpl) obj)._get_delegate();
            _set_delegate(delegate);
        } finally {
            orb.destroy();
        }
    }

    private void writeObject(ObjectOutputStream s) throws IOException {
        String[] args = null;
        Properties props = null;
        ORB orb = ORB.init(args, props);
        
        try {
            String str = orb.object_to_string(this);
            s.writeUTF(str);
        } finally {
            orb.destroy();
        }
    }
}