package br.com.orcamentop.negocio;

import br.com.orcamentop.dto.ListaOrcamento;
import br.com.orcamentop.dto.Orcamento;

/**
 * br/com/orcamentop/negocio/ControllerOrcamentoOperations.java . Generated by
 * the IDL-to-Java compiler (portable), version "3.2" from orcamentop.idl
 * Domingo, 10 de Junho de 2018 23h26min58s BRT
 */
public interface ControllerOrcamentoOperations {

    boolean gravar(Orcamento orcamento);

    boolean remover(Orcamento orcamento);

    ListaOrcamento carregar();
}
