package br.com.orcamentop.negocio;

import org.omg.CORBA.TypeCode;
import org.omg.CORBA.portable.InputStream;
import org.omg.CORBA.portable.OutputStream;
import org.omg.CORBA.portable.Streamable;

/**
 * br/com/orcamentop/negocio/ControllerProdutoHolder.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.2" from orcamentop.idl Domingo,
 * 10 de Junho de 2018 23h26min58s BRT
 */
public final class ControllerProdutoHolder implements Streamable {

    public ControllerProduto value = null;

    public ControllerProdutoHolder() {
    }

    public ControllerProdutoHolder(ControllerProduto initialValue) {
        value = initialValue;
    }

    @Override
    public void _read(InputStream i) {
        value = ControllerProdutoHelper.read(i);
    }

    @Override
    public void _write(OutputStream o) {
        ControllerProdutoHelper.write(o, value);
    }

    @Override
    public TypeCode _type() {
        return ControllerProdutoHelper.type();
    }
}
