package br.com.orcamentop.negocio;

import br.com.orcamentop.dto.ListaProduto;
import br.com.orcamentop.dto.Produto;

/**
 * br/com/orcamentop/negocio/ControllerProdutoOperations.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.2" from orcamentop.idl Domingo,
 * 10 de Junho de 2018 23h26min58s BRT
 */
public interface ControllerProdutoOperations {

    boolean gravar(Produto produto);

    boolean remover(Produto produto);

    ListaProduto carregar();
} // interface ControllerProdutoOperations
