package br.com.orcamentop.negocio;

import br.com.orcamentop.dto.ListaPessoa;
import br.com.orcamentop.dto.Pessoa;

/**
 * br/com/orcamentop/negocio/ControllerPessoaOperations.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.2" from orcamentop.idl Domingo,
 * 10 de Junho de 2018 23h26min58s BRT
 */
public interface ControllerPessoaOperations {

    boolean gravar(Pessoa pessoa);

    boolean remover(Pessoa pessoa);

    ListaPessoa carregar();
}