package br.com.orcamentop.negocio;

import org.omg.CORBA.TypeCode;
import org.omg.CORBA.portable.InputStream;
import org.omg.CORBA.portable.OutputStream;
import org.omg.CORBA.portable.Streamable;

/**
 * br/com/orcamentop/negocio/ControllerPessoaHolder.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.2" from orcamentop.idl Domingo,
 * 10 de Junho de 2018 23h26min58s BRT
 */
public final class ControllerPessoaHolder implements Streamable {

    public ControllerPessoa value = null;

    public ControllerPessoaHolder() {
    }

    public ControllerPessoaHolder(ControllerPessoa initialValue) {
        value = initialValue;
    }

    @Override
    public void _read(InputStream i) {
        value = ControllerPessoaHelper.read(i);
    }

    @Override
    public void _write(OutputStream o) {
        ControllerPessoaHelper.write(o, value);
    }

    @Override
    public TypeCode _type() {
        return ControllerPessoaHelper.type();
    }
}
