package br.com.orcamentop.negocio;

/**
 * br/com/orcamentop/negocio/ControllerPessoa.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.2" from orcamentop.idl Domingo,
 * 10 de Junho de 2018 23h26min58s BRT
 */
public interface ControllerPessoa extends ControllerPessoaOperations, 
        org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity {
}