package br.com.orcamentop.dto;

import java.util.ArrayList;
import java.util.List;
import org.omg.CORBA.Any;
import org.omg.CORBA.ORB;
import org.omg.CORBA.TypeCode;
import org.omg.CORBA.portable.InputStream;
import org.omg.CORBA.portable.OutputStream;

/**
 * br/com/orcamentop/ListaProdutoHelper.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from orcamentop.idl Domingo, 10 de Junho
 * de 2018 23h26min58s BRT
 */
abstract public class ListaProdutoHelper {

    private static String _id = "IDL:br/com/orcamentop/ListaProduto:1.0";

    public static void insert(Any a, ListaProduto that) {
        OutputStream out = a.create_output_stream();
        a.type(type());
        write(out, that);
        a.read_value(out.create_input_stream(), type());
    }

    public static ListaProduto extract(Any a) {
        return read(a.create_input_stream());
    }

    private static TypeCode __typeCode = null;

    synchronized public static TypeCode type() {
        if (__typeCode == null) {
            __typeCode = ProdutoHelper.type();
            __typeCode = ORB.init().create_sequence_tc(0, __typeCode);
            __typeCode = ORB.init().create_alias_tc(
                    ListaProdutoHelper.id(), 
                    "ListaProduto", 
                    __typeCode);
        }
        return __typeCode;
    }

    public static String id() {
        return _id;
    }

    public static ListaProduto read(InputStream istream) {
        List<Produto> list = new ArrayList<>();
        int len = istream.read_long();
        
        for (int i = 0; i < len; ++i) {
            list.add(ProdutoHelper.read(istream));
        }
        
        ListaProduto listaProduto = new ListaProduto(list);
        
        return listaProduto;
    }

    public static void write(OutputStream ostream, ListaProduto value) {
        int length = value.getLista().size();
        ostream.write_long(length);
        
        value.getLista().forEach((produto) -> {
            ProdutoHelper.write(ostream, produto);
        });
    }

}
