package br.com.orcamentop.dto;

/**
 * br/com/orcamentop/OrcamentoHolder.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from orcamentop.idl Domingo, 10 de Junho
 * de 2018 23h26min58s BRT
 */
public final class OrcamentoHolder implements org.omg.CORBA.portable.Streamable {

    public Orcamento value = null;

    public OrcamentoHolder() {
    }

    public OrcamentoHolder(Orcamento initialValue) {
        value = initialValue;
    }

    @Override
    public void _read(org.omg.CORBA.portable.InputStream i) {
        value = OrcamentoHelper.read(i);
    }

    @Override
    public void _write(org.omg.CORBA.portable.OutputStream o) {
        OrcamentoHelper.write(o, value);
    }

    @Override
    public org.omg.CORBA.TypeCode _type() {
        return OrcamentoHelper.type();
    }
}
