package br.com.orcamentop.dto;

import org.omg.CORBA.Any;
import org.omg.CORBA.ORB;
import org.omg.CORBA.StructMember;
import org.omg.CORBA.TCKind;
import org.omg.CORBA.TypeCode;
import org.omg.CORBA.portable.InputStream;
import org.omg.CORBA.portable.OutputStream;

/**
 * br/com/orcamentop/PessoaHelper.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from orcamentop.idl Domingo, 10 de Junho de 2018
 * 23h26min58s BRT
 */
abstract public class PessoaHelper {

    private static String _id = "IDL:br/com/orcamentop/Pessoa:1.0";
    private static org.omg.CORBA.TypeCode __typeCode = null;
    private static boolean __active = false;

    public static void insert(Any a, Pessoa that) {
        OutputStream out = a.create_output_stream();
        a.type(type());
        write(out, that);
        a.read_value(out.create_input_stream(), type());
    }

    public static Pessoa extract(Any a) {
        return read(a.create_input_stream());
    }

    synchronized public static TypeCode type() {
        if (__typeCode == null) {
            synchronized (TypeCode.class) {
                if (__typeCode == null) {
                    if (__active) {
                        return ORB.init().create_recursive_tc(_id);
                    }
                    
                    __active = true;
                    StructMember[] members = new StructMember[4];
                    TypeCode _tcOf_members0;
                    _tcOf_members0 = ORB.init().get_primitive_tc(TCKind.tk_long);
                    
                    members[0] = new StructMember(
                            "codigo",
                            _tcOf_members0,
                            null);
                    _tcOf_members0 = ORB.init().create_wstring_tc(0);
                    
                    members[1] = new StructMember(
                            "nome",
                            _tcOf_members0,
                            null);
                    _tcOf_members0 = ORB.init().create_wstring_tc(0);
                    
                    members[2] = new StructMember(
                            "telefone",
                            _tcOf_members0,
                            null);
                    _tcOf_members0 = ORB.init().create_wstring_tc(0);
                    
                    members[3] = new StructMember(
                            "email",
                            _tcOf_members0,
                            null);
                    
                    __typeCode = ORB.init().create_struct_tc(
                            PessoaHelper.id(), 
                            "Pessoa", 
                            members);
                    __active = false;
                }
            }
        }
        return __typeCode;
    }

    public static String id() {
        return _id;
    }

    public static Pessoa read(InputStream istream) {
        Pessoa value = new Pessoa();
        value.setCodigo(istream.read_long());
        value.setNome(istream.read_wstring());
        value.setTelefone(istream.read_wstring());
        value.setEmail(istream.read_wstring());
        return value;
    }

    public static void write(OutputStream ostream, Pessoa value) {
        ostream.write_long(value.getCodigo());
        ostream.write_wstring(value.getNome());
        ostream.write_wstring(value.getTelefone());
        ostream.write_wstring(value.getEmail());
    }

}
