package br.com.orcamentop.dto;

/**
 * br/com/orcamentop/Produto.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from orcamentop.idl Domingo, 10 de Junho de 2018
 * 23h26min58s BRT
 */
public final class Produto implements org.omg.CORBA.portable.IDLEntity {

    private int codigo = (int) 0;
    private String descricao = null;
    private double valor = (double) 0;

    public Produto() {
    }

    public int getCodigo() {
        return codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public double getValor() {
        return valor;
    }

    public void setValor(double valor) {
        this.valor = valor;
    }
}
