package br.com.orcamentop.dto;

import org.omg.CORBA.Any;
import org.omg.CORBA.ORB;
import org.omg.CORBA.StructMember;
import org.omg.CORBA.TCKind;
import org.omg.CORBA.TypeCode;
import org.omg.CORBA.portable.InputStream;
import org.omg.CORBA.portable.OutputStream;

/**
 * br/com/orcamentop/ProdutoHelper.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from orcamentop.idl Domingo, 10 de Junho de 2018
 * 23h26min58s BRT
 */
abstract public class ProdutoHelper {

    private static String _id = "IDL:br/com/orcamentop/Produto:1.0";
    private static TypeCode __typeCode = null;
    private static boolean __active = false;

    public static void insert(Any a, Produto that) {
        OutputStream out = a.create_output_stream();
        a.type(type());
        write(out, that);
        a.read_value(out.create_input_stream(), type());
    }

    public static Produto extract(Any a) {
        return read(a.create_input_stream());
    }


    synchronized public static TypeCode type() {
        if (__typeCode == null) {
            synchronized (TypeCode.class) {
                if (__typeCode == null) {
                    if (__active) {
                        return ORB.init().create_recursive_tc(_id);
                    }
                    __active = true;
                    StructMember[] members = new StructMember[3];
                    TypeCode tcOfMembers;
                    
                    tcOfMembers = ORB.init().get_primitive_tc(TCKind.tk_long);
                    members[0] = new StructMember(
                            "codigo",
                            tcOfMembers,
                            null);
                    
                    tcOfMembers = ORB.init().create_wstring_tc(0);
                    members[1] = new StructMember(
                            "descricao",
                            tcOfMembers,
                            null);
                    
                    tcOfMembers = ORB.init().get_primitive_tc(TCKind.tk_double);
                    members[2] = new StructMember(
                            "valor",
                            tcOfMembers,
                            null);
                    
                    __typeCode = ORB.init().create_struct_tc(ProdutoHelper.id(), "Produto", members);
                    __active = false;
                }
            }
        }
        return __typeCode;
    }

    public static String id() {
        return _id;
    }

    public static Produto read(InputStream istream) {
        Produto value = new Produto();
        value.setCodigo(istream.read_long());
        value.setDescricao(istream.read_wstring());
        value.setValor(istream.read_double());
        return value;
    }

    public static void write(OutputStream ostream, Produto value) {
        ostream.write_long(value.getCodigo());
        ostream.write_wstring(value.getDescricao());
        ostream.write_double(value.getValor());
    }
}
