package br.com.orcamentop.dto;

import org.omg.CORBA.TypeCode;
import org.omg.CORBA.portable.InputStream;
import org.omg.CORBA.portable.OutputStream;
import org.omg.CORBA.portable.Streamable;

/**
 * br/com/orcamentop/ProdutoHolder.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from orcamentop.idl Domingo, 10 de Junho de 2018
 * 23h26min58s BRT
 */
public final class ProdutoHolder implements Streamable {

    public Produto value = null;

    public ProdutoHolder() {
    }

    public ProdutoHolder(Produto initialValue) {
        value = initialValue;
    }

    @Override
    public void _read(InputStream i) {
        value = ProdutoHelper.read(i);
    }

    @Override
    public void _write(OutputStream o) {
        ProdutoHelper.write(o, value);
    }

    @Override
    public TypeCode _type() {
        return ProdutoHelper.type();
    }
}
