package br.com.orcamentop.persistencia;

/**
 * br/com/orcamentop/persistencia/PersistenciaOrcamento.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.2" from orcamentop.idl Domingo,
 * 10 de Junho de 2018 23h26min58s BRT
 */
public interface PersistenciaPessoa extends PersistenciaPessoaOperations, 
        org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity {
}