package br.com.orcamentop.persistencia;

import br.com.orcamentop.dto.ListaOrcamento;

/**
 * br/com/orcamentop/persistencia/PersistenciaOrcamentoOperations.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2" from
 * orcamentop.idl Domingo, 10 de Junho de 2018 23h26min58s BRT
 */
public interface PersistenciaOrcamentoOperations {

    boolean salvar(ListaOrcamento orcamento);

    ListaOrcamento carregar();
}